spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
  servlet:
    multipart:
      max-request-size: 500MB # request 요청 제한
      max-file-size: 500MB # 파일 업로드 크기 제한

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    defer-datasource-initialization: true

jwt:
  secretKey: ${JWT_SECRET_KEY}